spring:
  application:
    name: User
  cloud:
    config:
      enabled: true
      uri: http://localhost:1
  datasource:
    url: jdbc:mysql://localhost:3306/bdUser
    username: martinTingeso
    password: martinBD
  jpa:
    hibernate:
      ddl-auto: update