spring:
  application:
    name: User
  cloud:
    config:
      enabled: true
      uri: http://${DB_HOST}:8091
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/microBD
    username: martinTingeso
    password: martinBD
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 0